spring:
  cloud:
    gateway:
      routes:
        - id: railway-user-service
          uri: lb://railway-user-service
          predicates:
            - Path=/api/v1/user/**
        - id: railway-booking-service
          uri: lb://railway-booking-service
          predicates:
            - Path=/api/v1/booking/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 4000
