spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: railway-user-service
          uri: lb://railway-user-service
          predicates:
            - Path=/api/v1/user/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/booking/**

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/api/v2/spans
      export:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    hostname: gateway-service
server:
  port: 4000